"""add kehadiran table

Revision ID: 0e593cfa24d4
Revises: 31b0df543f5a
Create Date: 2026-05-07 19:12:45.781951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e593cfa24d4'
down_revision: Union[str, Sequence[str], None] = '31b0df543f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kehadiran',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_bap', sa.Integer(), nullable=False),
    sa.Column('id_mahasiswa', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_bap'], ['berita_acara_perkuliahan.id'], ),
    sa.ForeignKeyConstraint(['id_mahasiswa'], ['mahasiswa.id_mahasiswa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kehadiran')
    # ### end Alembic commands ###
