"""drop kelas column from mahasiswa

Revision ID: 1ec55da0dd3a
Revises: 2b9665e59601
Create Date: 2026-05-17 19:49:02.481446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1ec55da0dd3a'
down_revision: Union[str, Sequence[str], None] = '2b9665e59601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mahasiswa', 'kelas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahasiswa', sa.Column('kelas', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
