"""drop_kelas_kode_mk_semester_tahun_ajaran

Revision ID: 2b9665e59601
Revises: 8c8f37db093a
Create Date: 2026-05-10 23:17:15.466476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b9665e59601'
down_revision: Union[str, Sequence[str], None] = '8c8f37db093a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('kelas_ibfk_1'), 'kelas', type_='foreignkey')
    op.drop_column('kelas', 'semester')
    op.drop_column('kelas', 'tahun_ajaran')
    op.drop_column('kelas', 'kode_mk')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kelas', sa.Column('kode_mk', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('kelas', sa.Column('tahun_ajaran', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('kelas', sa.Column('semester', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('kelas_ibfk_1'), 'kelas', 'mata_kuliah', ['kode_mk'], ['kode_mk'])
    # ### end Alembic commands ###
