"""add_bap_table

Revision ID: 31b0df543f5a
Revises: 44e7d698a947
Create Date: 2026-05-07 18:54:13.656392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b0df543f5a'
down_revision: Union[str, Sequence[str], None] = '44e7d698a947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dosen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('berita_acara_perkuliahan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_dosen', sa.Integer(), nullable=False),
    sa.Column('id_kelas', sa.Integer(), nullable=False),
    sa.Column('id_mata_kuliah', sa.String(length=10), nullable=False),
    sa.Column('pertemuan_ke', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('materi', sa.String(length=255), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_dosen'], ['dosen.id'], ),
    sa.ForeignKeyConstraint(['id_kelas'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['id_mata_kuliah'], ['mata_kuliah.kode_mk'], ),
    sa.PrimaryKeyConstraint('id')
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('berita_acara_perkuliahan')
    op.drop_table('dosen')
    pass
    # ### end Alembic commands ###
