"""create remaining tables

Revision ID: 44e7d698a947
Revises: e2120dd1e405
Create Date: 2026-05-07 16:36:00.431952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e7d698a947'
down_revision: Union[str, Sequence[str], None] = 'e2120dd1e405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mata_kuliah',
    sa.Column('kode_mk', sa.String(length=10), nullable=False),
    sa.Column('nama_mk', sa.String(length=100), nullable=False),
    sa.Column('sks', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('kode_mk')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('kelas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_kelas', sa.String(length=50), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('tahun_ajaran', sa.String(length=20), nullable=False),
    sa.Column('kode_mk', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['kode_mk'], ['mata_kuliah.kode_mk'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kelas_mahasiswa',
    sa.Column('id_kelas_mahasiswa', sa.Integer(), nullable=False),
    sa.Column('mahasiswa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.id_mahasiswa'], ),
    sa.PrimaryKeyConstraint('id_kelas_mahasiswa')
    )
    op.create_index(op.f('ix_kelas_mahasiswa_id_kelas_mahasiswa'), 'kelas_mahasiswa', ['id_kelas_mahasiswa'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kelas_mahasiswa_id_kelas_mahasiswa'), table_name='kelas_mahasiswa')
    op.drop_table('kelas_mahasiswa')
    op.drop_table('kelas')
    op.drop_table('users')
    op.drop_table('mata_kuliah')
    # ### end Alembic commands ###
