"""create_kelas_dosen_table

Revision ID: 8c8f37db093a
Revises: a1b2c3d4e5f6
Create Date: 2026-05-10 21:50:20.064537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8f37db093a'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kelas_dosen',
    sa.Column('id_kelas_dosen', sa.Integer(), nullable=False),
    sa.Column('dosen_id', sa.Integer(), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dosen_id'], ['dosen.id'], ),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.PrimaryKeyConstraint('id_kelas_dosen')
    )
    op.create_index(op.f('ix_kelas_dosen_id_kelas_dosen'), 'kelas_dosen', ['id_kelas_dosen'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kelas_dosen_id_kelas_dosen'), table_name='kelas_dosen')
    op.drop_table('kelas_dosen')
    # ### end Alembic commands ###
