"""add_kelas_id_to_kelas_mahasiswa

Revision ID: 97cf41d84d2a
Revises: 0e593cfa24d4
Create Date: 2026-05-07 22:41:59.752834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97cf41d84d2a'
down_revision: Union[str, Sequence[str], None] = '0e593cfa24d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kelas_mahasiswa', sa.Column('kelas_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'kelas_mahasiswa', 'kelas', ['kelas_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kelas_mahasiswa', type_='foreignkey')
    op.drop_column('kelas_mahasiswa', 'kelas_id')
    # ### end Alembic commands ###
