"""create mahasiswa table

Revision ID: e2120dd1e405
Revises: 676bf226f1a5
Create Date: 2026-05-06 22:50:38.502769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2120dd1e405'
down_revision: Union[str, Sequence[str], None] = '676bf226f1a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('id_mahasiswa', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(length=11), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('kelas', sa.String(length=100), nullable=True),
    sa.Column('prodi', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_mahasiswa'),
    sa.UniqueConstraint('nim')
    )
    op.create_index(op.f('ix_mahasiswa_id_mahasiswa'), 'mahasiswa', ['id_mahasiswa'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mahasiswa_id_mahasiswa'), table_name='mahasiswa')
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###
