"""create berita acara perkuliahan table

Revision ID: f90154a33b37
Revises: 97cf41d84d2a
Create Date: 2026-05-10 20:47:43.832682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f90154a33b37'
down_revision: Union[str, Sequence[str], None] = '97cf41d84d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('berita_acara_perkuliahan', sa.Column('waktu_mulai', sa.Time(), nullable=False))
    op.add_column('berita_acara_perkuliahan', sa.Column('waktu_selesai', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('berita_acara_perkuliahan', 'waktu_selesai')
    op.drop_column('berita_acara_perkuliahan', 'waktu_mulai')
    # ### end Alembic commands ###
